<?php

/**
 * @file
 * Primary module hooks for Guestbook module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

/**
 * Implements hook_theme().
 */
function guestbook_theme($existing, $type, $theme, $path): array {
  return [
    'guestbook' => [
      'variables' => [
        'form' => NULL,
        'records' => [],
      ],
    ],
    'guestbook_record' => [
      'variables' => [
        'id' => NULL,
        'content' => NULL,
      ],
    ],
  ];
}
